name: langflipflop
channels:
  - conda-forge
  - defaults
dependencies:
  - astroid=2.6.5
  - ca-certificates=2021.7.5
  - certifi=2021.5.30
  - isort=5.9.2
  - lazy-object-proxy=1.6.0
  - libcxx=10.0.0
  - libffi=3.3
  - mccabe=0.6.1
  - ncurses=6.2
  - openssl=1.1.1k
  - pip=20.2.4
  - pylint=2.9.6
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - readline=8.1
  - setuptools=52.0.0
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.10
  - toml=0.10.2
  - wheel=0.36.2
  - wrapt=1.12.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - cachetools==4.2.2
    - charset-normalizer==2.0.4
    - google-api-core==1.31.1
    - google-auth==1.34.0
    - google-cloud-core==1.7.2
    - googleapis-common-protos==1.53.0
    - grpcio==1.39.0
    - idna==3.2
    - packaging==21.0
    - protobuf==3.17.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.7
    - pytz==2021.1
    - requests==2.26.0
    - rsa==4.7.2
    - urllib3==1.26.6
