AWSTemplateFormatVersion: '2010-09-09'
Description: S3 buckets for LangFlipFlop website
Transform: AWS::Serverless-2016-10-31

Parameters:
  Region:
    Type: String
    Default: 'us-east-1'

Resources:
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt CFNCustomProvider.Arn
      Principal: !GetAtt LambdaRole.Arn

  LambdaPolicy:
    Type: AWS::IAM::Policy
    DependsOn:
      - LambdaRole
    Properties:
      PolicyName: CFNCertificateDomainResourceRecordProvider
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - acm:RequestCertificate
              - acm:DescribeCertificate
              - acm:UpdateCertificateOptions
              - acm:DeleteCertificate
            Resource:
            - '*'
          - Effect: Allow
            Action:
              - logs:*
            Resource: arn:aws:logs:*:*:*
      Roles:
        - !Ref LambdaRole

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com

  CFNCustomProviderLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 7
      LogGroupName: !Sub '/aws/lambda/${CFNCustomProvider}'
    DependsOn:
      - CFNCustomProvider

  CFNCustomProvider:
    Type: AWS::Serverless::Function
    Properties:
      # TODO: grab from params
      CodeUri: 's3://langflipflop-external-us-east-1/cfn-certificate-provider-0.2.4.zip'
      Description: CFN Certificate Domain Resource Record Provider
      MemorySize: 128
      Handler: provider.handler
      Timeout: 300
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.6

  S3BucketLogs:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: LogDeliveryWrite
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  S3BucketRoot:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LoggingConfiguration:
        DestinationBucketName: !Ref 'S3BucketLogs'
        LogFilePrefix: 'origin/'
  
Outputs:
  S3BucketRoot:
    Description: Website bucket
    Value: !Ref S3BucketRoot
  S3BucketRootName:
    Description: Website bucket name
    Value: !GetAtt S3BucketRoot.DomainName
  S3BucketRootArn:
    Description: Website bucket locator
    Value: !GetAtt S3BucketRoot.Arn
  S3BucketLogs:
    Description: Logging bucket
    Value: !Ref S3BucketLogs
  S3BucketLogsName:
    Description: Logging bucket Name
    Value: !GetAtt S3BucketLogs.DomainName
  CFNCustomProvider:
    Description: ACM helper function
    Value: !GetAtt CFNCustomProvider.Arn
