name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm ci
      - run: make verify-ts
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          python-version: '3.8'
          auto-update-conda: true
          activate-environment: langflipflop
          auto-activate-base: false
      - run: |
          conda info
          conda list
          make verify-python
